description: Base DiffTracker on 4 datasets
target:
  # service: sing
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  # name: SingularityTestVC
  # workspace_name: SingularityTestWS
  # service: aml
  # name: usscv100cl
  # service: amlk8s
  # name: ms-shared
  service: sing
  name: msrresrchvc



environment:
  # image: zhangrh1908/swintrack:latest
  # registry: docker.io
  # username: zhangrh1908
  image: amlt-sing/pytorch-1.9.0-cuda11.3-cudnn8-devel:20221201T224031319
  # image: amlt-sing/pytorch-1.9.0-cuda11.3-a100:20221017T152211919  
  setup:
    - pip install -r requirements.txt --user

storage:
  input:
    storage_account_name: yczhaosc
    container_name: amulet
  external:
    storage_account_name: scim
    container_name: large-tracking-data

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR

data:
  storage_id: external
  remote_dir: train

# 提交之前检查datasets path
jobs:
- name: swint_5gt_encoder_dit_400_20_(3, 6)
  sku: G8-V100
  command:
  - python3 main.py SwinTrack Base --distributed_nproc_per_node 8 --distributed_do_spawn_workers --output_dir ./output --num_workers 24 --wandb_run_offline
  submit_args:
    env:
      {SHARED_MEMORY_PERCENT: 1}
  sla_tier: premium 
  execution_mode: basic
  priority: high
# jobs:
# - name: swint_5gt_encoder_dit_400_20_(3, 6)
#   sku: G8-V100
#   command:
#   # - python3 main.py SwinTrack Base --distributed_nproc_per_node 8 --distributed_do_spawn_workers --output_dir ./output --num_workers 24 --wandb_run_offline
#   - python3 main.py SwinTrack Base --distributed_nproc_per_node 8 --distributed_do_spawn_workers --output_dir ./output --num_workers 24 --wandb_run_offline
#   submit_args:
#     env:
#       {SHARED_MEMORY_PERCENT: 1}
#   sla_tier: premium
#   execution_mode: basic
#   priority: high

  # - python main.py SwinTrack Tiny --distributed_nproc_per_node 4 --distributed_do_spawn_workers --output_dir ./output --num_workers 24 --wandb_run_offline
#   # - bash run_simple.sh


# - name: train_tiny_swint
#   sku: G8
#   command:
#   - python main.py SwinTrack Tiny --output_dir ./output --num_workers 12 --wandb_run_offline
