filters:
  DataCleaning:
    AnnotationStandard:
      bounding_box_format: "XYXY"
      pixel_coordinate_system: "HalfPixelOffset"
      bounding_box_coordinate_system: "Spatial"
      pixel_definition: "Point"
    BoundingBox:
      fit_in_image_size: false
      update_validity: true
      remove_invalid_objects: true
      remove_empty_objects: true
    Integrity:
      remove_zero_annotation_objects: true
      remove_zero_annotation_image: false
      remove_zero_annotation_video_head_tail: false
      remove_invalid_image: true

datasets:
  # GOT10k:
    # type: 'SOT'
    # splits:
    #   - "val"
    #   - "test"

  LaSOT:
    type: 'SOT'
    splits:
      - "val"

  # LaSOT_Extension:
  #   type: 'SOT'
  #   splits:
  #     - "full"

  # TrackingNet:
  #   type: 'SOT'
  #   splits:
  #     - "test"
