mixin:
  fixed:
    - path: "runs.branch"
      value:
          test:
            training: false
            data: "test"
            runner: "test"
            epoch_interval: -1
            logging:
              interval: 10
              metric_prefix: "test_"
              local:
                header: "Test"
            metrics:
              enabled: true
              output_path: "test_metrics"
              handler:
                - type: "test_only"
                  name_regex: "got-10k-test"
                  packer:
                    path: "got10k"
                    format: "got10k"
                - type: "test_only"
                  name_regex: "trackingnet-test"
                  packer:
                    path: "trackingnet"
                    format: "trackingnet"
                - type: "standard"
            tracking:
              type: "SiamFC"
              curation_parameter_provider:
                type: "simple"
                min_object_size: [ 10, 10 ]
              window_penalty: 0.49
              cache:
                template:
                  type: "token"
                  dim: 512
                  length: 49 # 7 * 7
                image_mean:
                  type: "scalar"
                  dim: 3

            